export const directory = "img/exec/alumni";

export const alumni = [
  {
    name: "Ryan Xiao",
    position: "President",
    classYear: "2025",
    hometown: "Cary, NC",
    image: "ryanxiao.jpg",
  },
  {
    name: "Katie Liu",
    position: "President",
    classYear: "2025",
    hometown: "Naperville, IL",
    image: "katieliu.jpg",
  },
  {
    name: "Vivian Tan",
    position: "Community Chair",
    classYear: "2025",
    hometown: "Paramus, NJ",
    image: "viviantan.jpg",
  },
  {
    name: "Eric Hong",
    position: "Recruitment Chair",
    classYear: "2025",
    hometown: "Seattle, WA",
    image: "erichong.jpg",
  },
  {
    name: "Alex Lee",
    position: "Cultural Chair",
    classYear: "2025",
    hometown: "Weston, MA",
    image: "alexlee.jpeg",
  },
  {
    name: "Felix Huang",
    position: "Social Chair",
    classYear: "2025",
    hometown: "Rochester, NY",
    image: "felixhuang.jpg",
  },
  {
    name: "Celina Zhao",
    position: "President",
    classYear: "2024",
    hometown: "Athens, GA",
    image: "celinazhao.jpg",
  },
  {
    name: "Jesse Yang",
    position: "President",
    classYear: "2024",
    hometown: "Wilmette, IL",
    image: "jesseyang.jpeg",
  },
  {
    name: "Leon Deng",
    position: "Internal Social Chair",
    classYear: "2024",
    hometown: "Princeton, NJ",
    image: "leondeng.jpeg",
  },
  {
    name: "Eileen Li",
    position: "Member Outreach Chair",
    classYear: "2024",
    hometown: "Cupertino, CA",
    image: "eileenli.jpg",
  },
  {
    name: "Brianna Yao",
    position: "Publicity Designer",
    classYear: "2024",
    hometown: "Marlboro, NJ",
    image: "briannayao.jpg",
  },
  {
    name: "Haoran Wen",
    position: "Cultural Chair",
    classYear: "2024",
    hometown: "Brooklyn, NY",
    image: "haoranwen.jpeg",
  },

  {
    name: "Julia Xia",
    position: "Cultural Chair",
    classYear: "2024",
    hometown: "Queens, NY",
    image: "juliaxia.jpg",
  },
];

export const pastAlumni = [
  {
    year: "2023",
    names: [
      "Albert Luo",
      "Brigette Wang",
      "Helen Liu",
      "Jianna Liu",
      "Nina Wang",
      "Raina Thomas",
      "Sarah Chieng",
      "Vincent Wang",
    ],
  },
  {
    year: "2022",
    names: [
      "Andrew Shao",
      "Helen Lu",
      "Jenny Zhu",
      "Rachel Cheng",
      "Yujing Chen",
    ],
  },
  {
    year: "2021",
    names: [
      "Alex Guo",
      "Branden Morioka",
      "Kevin Fang",
      "Lillian Bu",
      "Xiqing Wang",
    ],
  },
  {
    year: "2020",
    names: ["Albert Go", "Hannah Chen", "Allen Lee"],
  },
  {
    year: "2019",
    names: ["Christie Hong", "Sarah Wu", "Alexandr Wang"],
  },
  {
    year: "2018",
    names: ["Dora Tzeng", "Selam Gano", "Sabrina", "Timothy Lu", "Amber Guo"],
  },
  {
    year: "2017",
    names: [
      "Katie Ho",
      "Tara Lee",
      "Jennifer Yu",
      "Karl Baranov",
      "Stephen Guo",
      "Tyson Chen",
      "Victor Zhang",
      "Mario Ho",
    ],
  },
  {
    year: "2016",
    names: [
      "Annie Kuan",
      "Brendan Chang",
      "Jessica Wang",
      "Kevin Tu",
      "Vicky Gong",
      "Kelly Liu",
    ],
  },
  {
    year: "2015",
    names: [
      "Anji Ren",
      "Brandon Le",
      "Nathalie Huynh",
      "Pat Capulong",
      "Sam Darryanto",
      "Frank (Xiao) Zhu",
      "Samantha Darryanto",
      "Thuan Doan",
    ],
  },
  {
    year: "2014",
    names: [
      "Angela Zhu",
      "Evan Wang",
      "Jennifer Kao",
      "Kristin Au",
      "Ruisi Shang",
      "Sherwin Wu",
      "Yi Wu",
      "Joseph Kim",
      "JJ Zhao / Jie Zhao",
    ],
  },
  {
    year: "2013",
    names: [
      "Liza Xu",
      "Thomas Schultz",
      "Christina Qi",
      "Terence Hsu",
      "David Tse",
    ],
  },
  {
    year: "2012",
    names: [
      "Rena Kuai",
      "Carter Chang",
      "Albert Kao",
      "Celena Chan",
      "Lisa Foo",
      "Michelle Lu",
      "Maggie Liu",
      "Eric Lau",
    ],
  },
  {
    year: "2011",
    names: [
      "Jacky Lau",
      "Nathan Li",
      "Charlie Huang",
      "Danielle Wang",
      "Danyi Wu",
      "Jeffrey Mo",
      "Kevin Pang",
    ],
  },
  {
    year: "2010",
    names: [
      "Stephanie Au",
      "Austin Tzou",
      "Qian Qian Tang",
      "Brandon Pung",
      "Glara Ahn",
      "Matt Huang",
    ],
  },
  {
    year: "2009",
    names: [
      "Gabe Chan",
      "Christine Yen",
      "Arjun Naskar",
      "Dan Hung",
      "Ting Ting Luo",
      "Albert Ni",
    ],
  },
  {
    year: "2008",
    names: [
      "Spencer Sugimoto",
      "Nick Nguyen",
      "Tara Chang Pettus",
      "Chris Wong",
      "Qin Liu",
      "Serena Lin",
      "Chen Liu",
    ],
  },
  {
    year: "2007",
    names: ["Weiyang Sun", "Michelle Law", "Grace Lo"],
  },
];
