export const directory = "img/exec/alumni";

export const alumni = [
  {
    name: "Ryan Xiao",
    position: "President",
    classYear: "2025",
    hometown: "Cary, NC",
    image: "ryanxiao.jpg",
  },
  {
    name: "Katie Liu",
    position: "President",
    classYear: "2025",
    hometown: "Naperville, IL",
    image: "katieliu.jpg",
  },
  {
    name: "Vivian Tan",
    position: "Community Chair",
    classYear: "2025",
    hometown: "Paramus, NJ",
    image: "viviantan.jpg",
  },
  {
    name: "Eric Hong",
    position: "Recruitment Chair",
    classYear: "2025",
    hometown: "Seattle, WA",
    image: "erichong.jpg",
  },
  {
    name: "Alex Lee",
    position: "Cultural Chair",
    classYear: "2025",
    hometown: "Weston, MA",
    image: "alexlee.jpeg",
  },
  {
    name: "Felix Huang",
    position: "Social Chair",
    classYear: "2025",
    hometown: "Rochester, NY",
    image: "felixhuang.jpg",
  },
  {
    name: "Brianna Yao",
    position: "Publicity Designer",
    classYear: "2024",
    hometown: "Marlboro, NJ",
    image: "briannayao.jpg",
  },
  {
    name: "Celina Zhao",
    position: "President",
    classYear: "2024",
    hometown: "Athens, GA",
    image: "celinazhao.jpg",
  },
  {
    name: "Jesse Yang",
    position: "President",
    classYear: "2024",
    hometown: "Wilmette, IL",
    image: "jesseyang.jpeg",
  },
  {
    name: "Leon Deng",
    position: "Internal Social Chair",
    classYear: "2024",
    hometown: "Princeton, NJ",
    image: "leondeng.jpeg",
  },
  {
    name: "Eileen Li",
    position: "Member Outreach Chair",
    classYear: "2024",
    hometown: "Cupertino, CA",
    image: "eileenli.jpg",
  },
  {
    name: "Haoran Wen",
    position: "Cultural Chair",
    classYear: "2024",
    hometown: "Brooklyn, NY",
    image: "haoranwen.jpeg",
  },

  {
    name: "Julia Xia",
    position: "Cultural Chair",
    classYear: "2024",
    hometown: "Queens, NY",
    image: "juliaxia.jpg",
  },
];
