export const current = [
  {
    name: "Thomas Wu",
    position: "President",
    classYear: "2026",
    hometown: "Austin, TX",
    image: "thomaswu.jpg",
  },
  {
    name: "Izzy Zhu",
    position: "President",
    classYear: "2026",
    hometown: "San Francisco, CA",
    image: "izzyzhu.jpg",
  },
  {
    name: "Charis Ching",
    position: "Treasurer",
    classYear: "2027",
    hometown: "Bay Area, CA",
    image: "charisching.jpg",
  },
  {
    name: "Livi Chen",
    position: "Treasurer",
    classYear: "2028",
    hometown: "Miami, FL",
    image: "livichen.jpg",
  },
  {
    name: "Christine Xu",
    position: "Philanthropy",
    classYear: "2026",
    hometown: "New York City, NY",
    image: "christinexu.jpg",
  },

  {
    name: "April Ren",
    position: "Philanthropy",
    classYear: "2027",
    hometown: "Seattle, WA",
    image: "aprilren.jpg",
  },
  {
    name: "Stanley Zhao",
    position: "Media Chair",
    classYear: "2027",
    hometown: "Long Island, NY",
    image: "stanleyzhao.jpg",
  },
  {
    name: "Krystal Montgomery",
    position: "Pub Chair",
    classYear: "2026",
    hometown: "Atlanta, GA",
    image: "krystalmontgomery.jpg",
  },
  {
    name: "Qingqing Ouyang",
    position: "Pub Chair",
    classYear: "2027",
    hometown: "Phoenix, AZ",
    image: "qingqingouyang.jpg",
  },
  {
    name: "Lisa Lin",
    position: "Pub Chair",
    classYear: "2028",
    hometown: "San Francisco, CA",
    image: "lisalin.png",
  },
  {
    name: "Jeff Zhu",
    position: "Cultural Chair",
    classYear: "2028",
    hometown: "Chicago, IL",
    image: "jeffzhu.jpg",
  },
  {
    name: "Kevin Xie",
    position: "Cultural Chair",
    classYear: "2028",
    hometown: "Denver, CO",
    image: "kevinxie.jpg",
  },
];
