export const directory = "img/exec/current";

export const current = [
  {
    name: "Charis Ching",
    position: "Co President",
    classYear: "2027",
    hometown: "Bay Area, CA",
    image: "charisching.jpg",
  },
  {
    name: "Stanley Zhao",
    position: "Co President",
    classYear: "2027",
    hometown: "Long Island, NY",
    image: "stanleyzhao.jpg",
  },
  {
    name: "Minnie Liang",
    position: "Co President",
    classYear: "2027",
    hometown: "West Lafayette, IN",
    image: "minnieliang.png",
  },
  {
    name: "Lisa Lin",
    position: "Historian",
    classYear: "2028",
    hometown: "Chattanooga, TN",
    image: "lisalin.png",
  },
  {
    name: "Livi Chen",
    position: "Treasurer/Merch Chair",
    classYear: "2028",
    hometown: "Dallas, TX",
    image: "livichen.jpg",
  },
  {
    name: "Ian Sun",
    position: "Treasurer/Food Chair",
    classYear: "2029",
    hometown: "Irvine, CA",
    image: "iansun.jpg",
  },
  {
    name: "Qingqing Ouyang",
    position: "Pub",
    classYear: "2027",
    hometown: "Oakland, MI",
    image: "qingqingouyang.jpg",
  },
  {
    name: "Ashlyn Gao",
    position: "Pub",
    classYear: "2029",
    hometown: "Miami, FL",
    image: "ashlyngao.jpg",
  },
  {
    name: "Jeff Zhu",
    position: "Cultural Chair",
    classYear: "2028",
    hometown: "Cincinnati, OH",
    image: "jeffzhu.jpg",
  },
  {
    name: "Rebecca Wang",
    position: "Community Chair",
    classYear: "2028",
    hometown: "Holmdel, NJ",
    image: "rebeccawang.jpeg",
  },
  {
    name: "Ethan Fang",
    position: "Community Chair",
    classYear: "2029",
    hometown: "Mason, OH",
    image: "ethanfang.jpg",
  },
  {
    name: "Lily Zhou",
    position: "CSChats Chair",
    classYear: "2029",
    hometown: "Seattle, WA",
    image: "lilyzhou.png",
  },
  {
    name: "Dalton Chi",
    position: "CSChats Chair",
    classYear: "2029",
    hometown: "Cerritos, CA",
    image: "daltonchi.jpeg",
  },
  {
    name: "April Ren",
    position: "External Affairs Chair",
    classYear: "2027",
    hometown: "New York City, NY",
    image: "aprilren.jpg",
  },
  {
    name: "Adam Sun",
    position: "Outreach Chair",
    classYear: "2027",
    hometown: "Phoenix, AZ",
    image: "adamsun.jpg",
  },
  {
    name: "Eric Ye",
    position: "Social Chair",
    classYear: "2028",
    hometown: "Cary, NC",
    image: "ericye.png",
  },
  {
    name: "Kathy Nie",
    position: "Social Chair",
    classYear: "2029",
    hometown: "Boise, ID",
    image: "kathynie.jpg",
  },
  {
    name: "Kevin Zhang",
    position: "Media Chair",
    classYear: "2028",
    hometown: "Pasadena, CA",
    image: "kevinzhang.png",
  },
  {
    name: "Matthew Zhou",
    position: "Food Chair",
    classYear: "2028",
    hometown: "Bellevue, WA",
    image: "matthewzhou.jpg",
  },
  {
    name: "Trish Zheng",
    position: "Food Chair",
    classYear: "2029",
    hometown: "Sarasota, FL",
    image: "trishzheng.jpeg",
  },
  {
    name: "Michelle Zhang",
    position: "Freshman Representative",
    classYear: "2030",
    hometown: "Chicago, IL",
    image: "michellezhang.jpg",
  },
  {
    name: "Alex Han",
    position: "Freshman Representative",
    classYear: "2030",
    hometown: "Long Grove, IL",
    image: "alexhan.jpg",
  },
  {
    name: "Iris Shen",
    position: "Freshman Representative",
    classYear: "2030",
    hometown: "Houston, TX",
    image: "irisshen.jpg",
  },
  {
    name: "Leaya Cleary",
    position: "Freshman Representative",
    classYear: "2030",
    hometown: "Los Gatos, CA",
    image: "leayacleary.jpg",
  },
];
