"use client";
import { useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import type { ElectionResults as Results } from '@/lib/voting/results';
const number = (n: number | null | undefined) => n == null ? '—' : n.toLocaleString(undefined,{maximumFractionDigits:2});
export default function ElectionResults({results, onBack, onEnd, busy}: {results: Results; onBack: ()=>void; onEnd?: ()=>void; busy?: boolean}) {
  const [criterionId,setCriterionId]=useState(results.criteria[0]?.id || '');
  const [candidateId,setCandidateId]=useState('all');
  const criterion=results.criteria.find(c=>c.id===criterionId);
  const visibleCandidates=candidateId === "all" ? results.candidates : results.candidates.filter(c=>c.candidate.id===candidateId);
  const selectedCandidate=candidateId === "all" ? undefined : visibleCandidates[0];
  const distribution=selectedCandidate?.stats.find(s=>s.criterionId===criterionId)?.distribution || [];
  const chart=visibleCandidates.map(c=>({name:c.candidate.name,Initial:c.stats.find(s=>s.criterionId===criterionId)?.initialAverage,Final:c.stats.find(s=>s.criterionId===criterionId)?.average}));
  return <section className="election-results voting-console">
    <header className="results-heading president-live-header"><div><h1>Results</h1></div><div className="results-actions">{results.spreadsheetUrl && <a href={results.spreadsheetUrl} target="_blank" rel="noreferrer">Open spreadsheet ↗</a>}<button onClick={onBack}>{results.ended ? 'New session' : 'Back to session'}</button>{onEnd && <button className="voting-end-session" disabled={busy} onClick={onEnd}>{busy ? "Ending…" : "End session"}</button>}</div></header>
    <div className="results-body">
    <div className="results-overview-filter"><label className="results-filter"><span>Show results for</span><select aria-label="Results candidate" value={candidateId} onChange={e=>setCandidateId(e.target.value)}><option value="all">All candidates</option>{results.candidates.map(c=><option key={c.candidate.id} value={c.candidate.id}>{c.candidate.name}</option>)}</select></label></div>
    {selectedCandidate ? <div className="results-candidate-overview"><h2>{selectedCandidate.candidate.name}</h2><div className="results-totals"><div><strong>{selectedCandidate.ballots.length}</strong><span>Voters who rated this candidate</span></div><div><strong>{selectedCandidate.stats.filter(s=>s.count>0).length} / {results.criteria.length}</strong><span>Criteria with ratings</span></div></div></div> : <div className="results-totals"><div><strong>{visibleCandidates.length}</strong><span>Candidates</span></div><div><strong>{results.voterCount}</strong><span>Voters joined</span></div><div><strong>{visibleCandidates.reduce((n,c)=>n+c.ballots.length,0)}</strong><span>Votes submitted</span></div></div>}
    {!visibleCandidates.some(c=>c.ballots.length) && <p className="results-empty" role="status">No submitted votes for this selection yet. Saved initial ratings are not counted as votes.</p>}
    {!selectedCandidate && <>
    <section className="results-section"><h2>Candidate summary</h2><p>Average submitted scores for each criterion, matching the spreadsheet summary. Unrated criteria are excluded.</p><div className="results-table results-summary-table" style={{height:Math.min(360,100 + results.candidates.length*48)}}><table><thead><tr><th>Candidate</th>{results.criteria.map(c=><th key={c.id}>{c.label}</th>)}<th>Votes</th></tr></thead><tbody>{visibleCandidates.map(c=><tr key={c.candidate.id}><th>{c.candidate.name}{!c.candidate.completed && <small>Incomplete</small>}</th>{c.stats.map(s=><td key={s.criterionId}>{number(s.average)}</td>)}<td>{c.ballots.length}</td></tr>)}</tbody></table></div></section>
    <section className="results-section"><div className="results-section-heading"><h2>Scores by criterion</h2><label className="results-filter"><select aria-label="Chart criterion" value={criterionId} onChange={e=>setCriterionId(e.target.value)}>{results.criteria.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label></div><p>Average submitted scores. Scale: {criterion?.min}–{criterion?.max}.</p><div className="results-chart" style={{height:Math.min(360,Math.max(180,results.candidates.length*64+64))}}><div style={{height:Math.max(154,chart.length*64+40),minWidth:280}}><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer={false} layout="vertical" data={chart} margin={{top:16,right:8,left:0,bottom:8}}><CartesianGrid stroke="#ffffff0d" vertical={false}/><YAxis type="category" dataKey="name" width={140} tickFormatter={name=>String(name).length>20 ? String(name).slice(0,19)+"…" : String(name)} tick={{fill:'#aaa',fontSize:12}}/><XAxis type="number" domain={[Math.min(0,criterion?.min ?? 0),criterion?.max ?? 5]} tick={{fill:'#aaa',fontSize:12}}/><Tooltip cursor={false} contentStyle={{background:'#19191b',border:'1px solid #333',borderRadius:8,color:'#eee'}} formatter={v=>number(typeof v==='number'?v:null)}/><Bar name="Average score" dataKey="Final" fill="#ed1934" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></div></section>
    </>}
    <section className="results-section"><div className="results-section-heading"><h2>{selectedCandidate ? "Scores across criteria" : "Vote breakdown"}</h2></div>{visibleCandidates.map(selected=><div className="results-candidate-breakdown" key={selected.candidate.id}>{!selectedCandidate && <p className="results-selected-label">{selected.candidate.name}</p>}<p>{selected.ballots.length} votes submitted. Banned voters’ ballots are excluded.</p><div className="results-table"><table><thead><tr><th>Criterion</th><th>Ratings</th><th>Average</th><th>Median</th><th>Scores received</th></tr></thead><tbody>{selected.stats.map(s=><tr key={s.criterionId}><th>{results.criteria.find(c=>c.id===s.criterionId)?.label}</th><td>{s.count}</td><td>{number(s.average)}</td><td>{number(s.median)}</td><td>{s.count ? (s.min === s.max ? number(s.min) : `${number(s.min)}–${number(s.max)}`) : '—'}</td></tr>)}</tbody></table></div><details className="results-ballots"><summary>Votes by person ({selected.ballots.length})</summary><p>Each row shows one person’s submitted scores for this candidate.</p><div className="results-table"><table><thead><tr><th>Voter</th>{results.criteria.map(c=><th key={c.id}>{c.label}</th>)}<th>Submitted</th></tr></thead><tbody>{selected.ballots.map(b=><tr key={b.voterId}><th>{b.voterName}</th>{results.criteria.map(c=><td key={c.id}>{number(b.final[c.id])}</td>)}<td>{new Date(b.submittedAt).toLocaleString()}</td></tr>)}</tbody></table>{!selected.ballots.length && <p>No votes submitted.</p>}</div></details></div>)}</section>
    {selectedCandidate && <section className="results-section"><div className="results-section-heading"><h2>Rating distribution</h2><label className="results-filter"><select aria-label="Distribution criterion" value={criterionId} onChange={e=>setCriterionId(e.target.value)}>{results.criteria.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label></div><p>How many voters chose each score. Scale: {criterion?.min}–{criterion?.max}.</p><div className="results-chart" style={{height:240}}><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer={false} data={Array.from({length:Math.max(0,(criterion?.max ?? 0)-(criterion?.min ?? 0)+1)},(_,i)=>{const rating=(criterion?.min ?? 0)+i;return {rating,count:distribution.find(d=>d.rating===rating)?.count || 0};})}><XAxis dataKey="rating" tick={{fill:'#aaa',fontSize:12}}/><YAxis allowDecimals={false} tick={{fill:'#aaa',fontSize:12}}/><Tooltip cursor={false} contentStyle={{background:'#19191b',border:'1px solid #333',borderRadius:8}}/><Bar name="Voters" dataKey="count" fill="#ed1934" isAnimationActive={false}/></BarChart></ResponsiveContainer></div></section>}
    <details className="results-history"><summary>Rating changes during discussion</summary>{selectedCandidate ? <div className="results-table"><table><thead><tr><th>Criterion</th><th>Initial average</th><th>Final average</th><th>Change</th></tr></thead><tbody>{selectedCandidate.stats.map(s=><tr key={s.criterionId}><th>{results.criteria.find(c=>c.id===s.criterionId)?.label}</th><td>{number(s.initialAverage)}</td><td>{number(s.average)}</td><td>{s.average != null && s.initialAverage != null ? number(s.average-s.initialAverage) : '—'}</td></tr>)}</tbody></table></div> :     <section className="results-section"><div className="results-section-heading"><h2>Before & after discussion</h2><label className="results-filter"><select aria-label="Comparison criterion" value={criterionId} onChange={e=>setCriterionId(e.target.value)}>{results.criteria.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label></div><p>Initial and final averages from submitted final ballots. Scale: {criterion?.min}–{criterion?.max}.</p><div className="results-chart" style={{height:Math.min(360,Math.max(180,results.candidates.length*64+64))}}><div style={{height:Math.max(154,chart.length*64+40),minWidth:280}}><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer={false} layout="vertical" data={chart} margin={{top:16,right:8,left:0,bottom:8}}><CartesianGrid stroke="#ffffff0d" vertical={false}/><YAxis type="category" dataKey="name" width={140} tickFormatter={name=>String(name).length>20 ? String(name).slice(0,19)+"…" : String(name)} tick={{fill:'#aaa',fontSize:12}}/><XAxis type="number" domain={[Math.min(0,criterion?.min ?? 0),criterion?.max ?? 5]} tick={{fill:'#aaa',fontSize:12}}/><Tooltip cursor={false} contentStyle={{background:'#19191b',border:'1px solid #333',borderRadius:8,color:'#eee'}} formatter={v=>number(typeof v==='number'?v:null)}/><Legend/><Bar dataKey="Initial" fill="#626269" radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="Final" fill="#ed1934" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></div></section>
    } </details>
    </div>
  </section>;
}
